# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: McLeans Ice Cream
email: info@mcleansicecream.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mcleansicecream.com" # the base hostname & protocol for your site
phone_text: '01764 681749'
phone_url: '+441764681749'
opening_hours:
- days: 'Tues - Sat'
  hours: '11am - 9pm'
- days: 'Sun & Mon'
  hours: 'Closed'

# Links
facebook_url: 'https://www.facebook.com/Mcleans-Ice-Cream-Parlour-and-Pizzeria-215720468797870'

nav:
- title: Menu
  url: menu.html

# Build settings
markdown: kramdown
